# Jekyll configuration for Noted documentation
title: Noted
description: A VS Code extension for organized workspace notes with templates, search, and daily tracking
baseurl: "/noted"
url: "https://jsonify.github.io"

# Theme configuration
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

# Just the Docs theme settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable aux links (top navigation buttons)
aux_links:
  "View on GitHub":
    - "https://github.com/jsonify/noted"
  "Install Extension":
    - "https://marketplace.visualstudio.com/items?itemName=jsonify.noted"

aux_links_new_tab: true

# Color scheme
color_scheme: nil

# Footer content
footer_content: 'Copyright &copy; 2025 Noted. Distributed by an <a href="https://github.com/jsonify/noted/blob/main/LICENSE">MIT license.</a>'

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchor links
heading_anchors: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Include/Exclude
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - AUTOMATED_TESTING.md
  - brief.md
  - DEVELOPMENT_SCRIPTS_GUIDE.md
  - LOCKFILE_NOTE.md
  - PAT_SETUP.md
  - PUBLISHING.md
  - QUICK_REFERENCE.md
  - test-summary.md
  - TESTING.md
  - VERIFICATION_RESULTS.md
  - WORKFLOW_HEALTH_CHECK.md
  - WORKFLOWS.md

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
